var hierarchy =
[
    [ "_G", "class___g.html", null ],
    [ "any", "classany.html", null ],
    [ "core::async", "classcore_1_1async.html", null ],
    [ "plus::BinaryReader", "classplus_1_1_binary_reader.html", null ],
    [ "plus::BinaryWriter", "classplus_1_1_binary_writer.html", null ],
    [ "bit", "classbit.html", null ],
    [ "boolean", "classboolean.html", null ],
    [ "ffi::callback", "classffi_1_1callback.html", null ],
    [ "ffi::cdata", "classffi_1_1cdata.html", null ],
    [ "math::collision", "classmath_1_1collision.html", null ],
    [ "x::color", "classx_1_1color.html", null ],
    [ "lstg::Color", "classlstg_1_1_color.html", null ],
    [ "coroutine", "classcoroutine.html", null ],
    [ "debug", "classdebug.html", null ],
    [ "debug::DebugInfo", "classdebug_1_1_debug_info.html", null ],
    [ "math::distance", "classmath_1_1distance.html", null ],
    [ "audio::Effect", "classaudio_1_1_effect.html", null ],
    [ "audio::Engine", "classaudio_1_1_engine.html", null ],
    [ "x::EventDispatcher", "classx_1_1_event_dispatcher.html", null ],
    [ "x::EventListener", "classx_1_1_event_listener.html", null ],
    [ "ffi", "classffi.html", null ],
    [ "file", "classfile.html", null ],
    [ "lstg::FileDialog", "classlstg_1_1_file_dialog.html", null ],
    [ "plus::FileSeekOrigin", "classplus_1_1_file_seek_origin.html", null ],
    [ "plus::FileStream", "classplus_1_1_file_stream.html", null ],
    [ "x::FileSystem", "classx_1_1_file_system.html", null ],
    [ "audio::Filter", "classaudio_1_1_filter.html", null ],
    [ "function", "classfunction.html", null ],
    [ "math::geometry", "classmath_1_1geometry.html", null ],
    [ "math::hull", "classmath_1_1hull.html", null ],
    [ "imgui::ImDrawList", "classimgui_1_1_im_draw_list.html", null ],
    [ "imgui::ImFont", "classimgui_1_1_im_font.html", null ],
    [ "imgui::helper::imgui::ImFontAtlas", "classimgui_1_1helper_1_1imgui_1_1_im_font_atlas.html", null ],
    [ "imgui::ImFontAtlas", "classimgui_1_1_im_font_atlas.html", null ],
    [ "imgui::ImFontAtlasCustomRect", "classimgui_1_1_im_font_atlas_custom_rect.html", null ],
    [ "imgui::helper::imgui::ImFontConfig", "classimgui_1_1helper_1_1imgui_1_1_im_font_config.html", null ],
    [ "imgui::ImFontConfig", "classimgui_1_1_im_font_config.html", null ],
    [ "imgui::ImFontGlyph", "classimgui_1_1_im_font_glyph.html", null ],
    [ "imgui", "classimgui.html", null ],
    [ "imgui::ImGuiIO", "classimgui_1_1_im_gui_i_o.html", null ],
    [ "imgui::ImGuiStyle", "classimgui_1_1_im_gui_style.html", null ],
    [ "imgui::ImGuiViewport", "classimgui_1_1_im_gui_viewport.html", null ],
    [ "implot", "classimplot.html", null ],
    [ "implot::ImPlotInputMap", "classimplot_1_1_im_plot_input_map.html", null ],
    [ "implot::ImPlotLimits", "classimplot_1_1_im_plot_limits.html", null ],
    [ "implot::ImPlotPoint", "classimplot_1_1_im_plot_point.html", null ],
    [ "implot::ImPlotRange", "classimplot_1_1_im_plot_range.html", null ],
    [ "implot::ImPlotStyle", "classimplot_1_1_im_plot_style.html", null ],
    [ "math::intersection", "classmath_1_1intersection.html", null ],
    [ "util::io", "classutil_1_1io.html", null ],
    [ "io", "classio.html", null ],
    [ "jit", "classjit.html", null ],
    [ "json", "classjson.html", null ],
    [ "lfs", "classlfs.html", null ],
    [ "std::list", "classstd_1_1list.html", null ],
    [ "std::list_iterator", "classstd_1_1list__iterator.html", null ],
    [ "local", "classlocal.html", null ],
    [ "lfs::lock", "classlfs_1_1lock.html", null ],
    [ "lstg::LogSystem", "classlstg_1_1_log_system.html", null ],
    [ "lstg", "classlstg.html", null ],
    [ "math::mat4", "classmath_1_1mat4.html", null ],
    [ "math", "classmath.html", null ],
    [ "math::matrix", "classmath_1_1matrix.html", null ],
    [ "nil", "classnil.html", null ],
    [ "Node", null, [
      [ "im::Widget", "classim_1_1_widget.html", [
        [ "im::About", "classim_1_1_about.html", null ],
        [ "im::Bullet", "classim_1_1_bullet.html", null ],
        [ "im::Button", "classim_1_1_button.html", null ],
        [ "im::Checkbox", "classim_1_1_checkbox.html", null ],
        [ "im::ChildWindow", "classim_1_1_child_window.html", null ],
        [ "im::CollapsingHeader", "classim_1_1_collapsing_header.html", null ],
        [ "im::Combo", "classim_1_1_combo.html", null ],
        [ "im::Console", "classim_1_1_console.html", null ],
        [ "im::ImageButton", "classim_1_1_image_button.html", null ],
        [ "im::InputText", "classim_1_1_input_text.html", null ],
        [ "im::LogWindow", "classim_1_1_log_window.html", null ],
        [ "im::lstg::GameResInfo", "classim_1_1lstg_1_1_game_res_info.html", null ],
        [ "im::lstg::KeyState", "classim_1_1lstg_1_1_key_state.html", null ],
        [ "im::lstg::PerformanceInfo", "classim_1_1lstg_1_1_performance_info.html", null ],
        [ "im::lstg::THlibInfo", "classim_1_1lstg_1_1_t_hlib_info.html", null ],
        [ "im::ProgressBar", "classim_1_1_progress_bar.html", null ],
        [ "im::RadioButton", "classim_1_1_radio_button.html", null ],
        [ "im::RadioButtonGroup", "classim_1_1_radio_button_group.html", null ],
        [ "im::Selectable", "classim_1_1_selectable.html", null ],
        [ "im::SelectableGroup", "classim_1_1_selectable_group.html", null ],
        [ "im::TabBar", "classim_1_1_tab_bar.html", null ],
        [ "im::TabItem", "classim_1_1_tab_item.html", null ],
        [ "im::Text", "classim_1_1_text.html", null ],
        [ "im::TreeNode", "classim_1_1_tree_node.html", null ],
        [ "im::VariableWatch", "classim_1_1_variable_watch.html", null ],
        [ "im::Window", "classim_1_1_window.html", [
          [ "im::lstg::GameInfo", "classim_1_1lstg_1_1_game_info.html", null ],
          [ "im::StyleSetting", "classim_1_1_style_setting.html", null ]
        ] ]
      ] ],
      [ "imgui::ColorTextEdit", "classimgui_1_1_color_text_edit.html", null ],
      [ "lstg::Latex", "classlstg_1_1_latex.html", null ]
    ] ],
    [ "number", "classnumber.html", [
      [ "audio::EffectDirection", "classaudio_1_1_effect_direction.html", null ],
      [ "audio::EffectPhoneme", "classaudio_1_1_effect_phoneme.html", null ],
      [ "audio::EffectWaveform", "classaudio_1_1_effect_waveform.html", null ]
    ] ],
    [ "object", "classobject.html", [
      [ "xobject", "classxobject.html", [
        [ "xobject3d", "classxobject3d.html", null ]
      ] ]
    ] ],
    [ "lstg::ZipArchive::OpenMode", "classlstg_1_1_zip_archive_1_1_open_mode.html", null ],
    [ "jit::opt", "classjit_1_1opt.html", null ],
    [ "os", "classos.html", null ],
    [ "package", "classpackage.html", null ],
    [ "plus", "classplus.html", null ],
    [ "profiler", "classprofiler.html", null ],
    [ "math::quaternion", "classmath_1_1quaternion.html", null ],
    [ "lstg::Rand", "classlstg_1_1_rand.html", null ],
    [ "math::Random", "classmath_1_1_random.html", null ],
    [ "lstg::Random", "classlstg_1_1_random.html", null ],
    [ "x::range", "classx_1_1range.html", null ],
    [ "Ref", null, [
      [ "audio::Decoder", "classaudio_1_1_decoder.html", null ],
      [ "audio::RecordingDevice", "classaudio_1_1_recording_device.html", null ],
      [ "audio::Source", "classaudio_1_1_source.html", null ],
      [ "audio::Stream", "classaudio_1_1_stream.html", null ],
      [ "lstg::Buffer", "classlstg_1_1_buffer.html", null ],
      [ "lstg::GameObjectBentLaser", "classlstg_1_1_game_object_bent_laser.html", null ],
      [ "lstg::ParticlePool", "classlstg_1_1_particle_pool.html", null ],
      [ "lstg::Resource", "classlstg_1_1_resource.html", [
        [ "lstg::ResAudio", "classlstg_1_1_res_audio.html", [
          [ "lstg::ResMusic", "classlstg_1_1_res_music.html", null ],
          [ "lstg::ResSound", "classlstg_1_1_res_sound.html", null ]
        ] ],
        [ "lstg::ResFont", "classlstg_1_1_res_font.html", null ],
        [ "lstg::ResFX", "classlstg_1_1_res_f_x.html", null ],
        [ "lstg::ResourceColliable", "classlstg_1_1_resource_colliable.html", [
          [ "lstg::ResourceQuad", "classlstg_1_1_resource_quad.html", [
            [ "lstg::ResAnimation", "classlstg_1_1_res_animation.html", null ],
            [ "lstg::ResSprite", "classlstg_1_1_res_sprite.html", null ]
          ] ],
          [ "lstg::ResParticle", "classlstg_1_1_res_particle.html", null ]
        ] ]
      ] ],
      [ "lstg::ResourcePack", "classlstg_1_1_resource_pack.html", null ],
      [ "lstg::Stream", "classlstg_1_1_stream.html", [
        [ "lstg::StreamFile", "classlstg_1_1_stream_file.html", null ],
        [ "lstg::StreamMemory", "classlstg_1_1_stream_memory.html", null ]
      ] ],
      [ "lstg::Triangles", "classlstg_1_1_triangles.html", null ],
      [ "lstg::WindowHelper", "classlstg_1_1_window_helper.html", [
        [ "lstg::WindowHelperDesktop", "classlstg_1_1_window_helper_desktop.html", null ]
      ] ],
      [ "lstg::ZipArchive", "classlstg_1_1_zip_archive.html", null ]
    ] ],
    [ "lstg::RenderMode", "classlstg_1_1_render_mode.html", null ],
    [ "plus::ReplayFrameReader", "classplus_1_1_replay_frame_reader.html", null ],
    [ "plus::ReplayFrameWriter", "classplus_1_1_replay_frame_writer.html", null ],
    [ "plus::ReplayManager", "classplus_1_1_replay_manager.html", null ],
    [ "lstg::ResourceMgr", "classlstg_1_1_resource_mgr.html", null ],
    [ "lstg::ResRenderTarget", "classlstg_1_1_res_render_target.html", null ],
    [ "lstg::ResTexture", "classlstg_1_1_res_texture.html", null ],
    [ "audio::SoundData", "classaudio_1_1_sound_data.html", null ],
    [ "_G::soundVolume", "class___g_1_1sound_volume.html", null ],
    [ "math::spline", "classmath_1_1spline.html", null ],
    [ "Sprite", null, [
      [ "video::Player", "classvideo_1_1_player.html", null ]
    ] ],
    [ "core::stage", "classcore_1_1stage.html", null ],
    [ "lstg::ZipArchive::State", "classlstg_1_1_zip_archive_1_1_state.html", null ],
    [ "std", "classstd.html", null ],
    [ "lstg::StopWatch", "classlstg_1_1_stop_watch.html", null ],
    [ "string", "classstring.html", null ],
    [ "imgui::style", "classimgui_1_1style.html", null ],
    [ "table", "classtable.html", null ],
    [ "task", "classtask.html", null ],
    [ "im::TextFilter", "classim_1_1_text_filter.html", null ],
    [ "thread", "classthread.html", null ],
    [ "math::tween", "classmath_1_1tween.html", null ],
    [ "userdata", "classuserdata.html", null ],
    [ "utf8", "classutf8.html", null ],
    [ "lstg::util", "classlstg_1_1util.html", null ],
    [ "jit::util", "classjit_1_1util.html", null ],
    [ "math::vec2", "classmath_1_1vec2.html", null ],
    [ "vec2_table", null, [
      [ "ImVec2", "class_im_vec2.html", null ]
    ] ],
    [ "math::vec3", "classmath_1_1vec3.html", null ],
    [ "math::vec4", "classmath_1_1vec4.html", null ],
    [ "vec4_table", null, [
      [ "ImVec4", "class_im_vec4.html", null ]
    ] ],
    [ "vector", "classvector.html", null ],
    [ "Widget", null, [
      [ "l2d::Model", "classl2d_1_1_model.html", null ]
    ] ],
    [ "lstg::World", "classlstg_1_1_world.html", null ]
];