---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Xrysnow.
--- DateTime: 2023/1/9 23:55
---

fgui = fgui or {}

---@type fgui.GObject
local GObject = {}

---@return fgui.GComponent
function GObject:asGComponent()
end

---@return fgui.GGraph
function GObject:asGGraph()
end

---@return fgui.GGroup
function GObject:asGGroup()
end

---@return fgui.GLoader
function GObject:asGLoader()
end

---@return fgui.GLoader3D
function GObject:asGLoader3D()
end

---@return fgui.GMovieClip
function GObject:asGMovieClip()
end

---@return fgui.GTextField
function GObject:asGTextField()
end

---@return fgui.GImage
function GObject:asGImage()
end

---@return fgui.GBasicTextField
function GObject:asGBasicTextField()
end

---@return fgui.GTextInput
function GObject:asGTextInput()
end

---@return fgui.GRichTextField
function GObject:asGRichTextField()
end

---@return fgui.GComboBox
function GObject:asGComboBox()
end

---@return fgui.GScrollBar
function GObject:asGScrollBar()
end

---@return fgui.Window
function GObject:asWindow()
end

---@return fgui.GRoot
function GObject:asGRoot()
end

---@return fgui.GProgressBar
function GObject:asGProgressBar()
end

---@return fgui.GButton
function GObject:asGButton()
end

---@return fgui.GSlider
function GObject:asGSlider()
end

---@return fgui.GList
function GObject:asGList()
end

---@return fgui.GLabel
function GObject:asGLabel()
end

---@return fgui.GTree
function GObject:asGTree()
end
